In [2]:
# write a UDF to sum n numbers?
def fn_sum2no( *args ):
    
    # declare a variable to hold the total value
    Sum = 0
    
    # run the loop for each value in the iterable
    for i in args:
        
        # check if the value is a number
        if type(i) == int or type(i) == float:
            
            # sum the value
            Sum += i
    
    return Sum

In [3]:
fn_sum2no( 1, 2, 3, 4, 'Python' )

10

In [4]:
fn_sum2no()

0

### lambda functions

In [5]:
# UDF to sum two numbers
def sum2no(x, y):
    return x + y

In [6]:
lambda x, y: x + y

<function __main__.<lambda>(x, y)>

In [7]:
# write a udf to add number 10 to the values in the list
def fn_example1( lst ):
    
    l2 = []
    for i in lst:
        l2.append(i + 10)
    return l2

In [8]:
# list
l1 = [1, 2, 3, 4, 5]

# call the UDF
fn_example1( l1 )

[11, 12, 13, 14, 15]

In [9]:
# list
l1 = [1, 2, 3, 4, 5]

# map function along with lambda function
list(map( lambda x : x + 10, l1 ) )

[11, 12, 13, 14, 15]

In [10]:
l2 = [1, 2, 3, 4, 5, 4, 3, 3, 4, 5, 6, 7, 8, 1, 1, 3, 5]

In [11]:
# UDF to return only even numbers from given iterable
def fn_get_even_no( lst ):
    
    l3 = []
    for i in lst:
        if i % 2 == 0:
            l3.append( i )
    return l3

In [12]:
fn_get_even_no(l2)

[2, 4, 4, 4, 6, 8]

In [13]:
list(filter( lambda x : x % 2 == 0, l2 ))

[2, 4, 4, 4, 6, 8]

In [14]:
fn_new = lambda x : x % 2 == 0

In [15]:
fn_new(10)

True

In [16]:
list(filter( lambda x : x % 2 == 0, l2 ))

[2, 4, 4, 4, 6, 8]

In [17]:
list(map( lambda y : y + 100, list(filter( lambda x : x % 2 == 0, l2 ))))

[102, 104, 104, 104, 106, 108]

In [18]:
var = 'Python'

for i in var:
    print(i)

P
y
t
h
o
n


## numpy - numerical python

In [19]:
import numpy as np

In [20]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [21]:
l1 = list(range(10))

In [22]:
type(l1)

list

In [23]:
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
a1 = np.array( l1 )

In [25]:
a2 = np.array( l1, dtype = 'int8')

In [26]:
type(a1)

numpy.ndarray

In [27]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

#### attributes

.ndim, .shape, .size, .nbytes

In [29]:
a1.nbytes

40

In [30]:
a2.nbytes

10

In [31]:
a1.ndim

1

In [32]:
a1.shape

(10,)

In [33]:
a1.size

10

In [34]:
a3 = np.zeros( (2, 3, 4) )

In [35]:
a4 = np.ones( shape = (3, 3) )

In [36]:
a5 = np.full( (3, 6), 'Python' )

In [37]:
a3.ndim

3

In [38]:
a3.shape

(2, 3, 4)

In [39]:
a3.size

24

In [40]:
np.array( range(0, 5, 1) )

array([0, 1, 2, 3, 4])

In [41]:
np.arange(0.5, 5, 0.1)

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7,
       1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ,
       3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3,
       4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [42]:
np.linspace( 10, 20, 4 )

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [43]:
np.random.random( 20 )

array([0.89103535, 0.62331922, 0.18523037, 0.12775933, 0.8548471 ,
       0.43880954, 0.39384128, 0.89134437, 0.25470226, 0.70673512,
       0.91447919, 0.2758905 , 0.63541334, 0.90486945, 0.54495382,
       0.41308776, 0.87298004, 0.05439507, 0.13138135, 0.30548388])

In [44]:
a7 = np.random.randint( 10, 100, 20 )

In [45]:
a6 = np.arange( 0, 1.00, 0.01 )

In [46]:
a6.size

100

In [47]:
a6.ndim

1

##### reshape requires the size in the input and output to be same

In [48]:
a6.reshape( 5, 20 )

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
        0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ,
        0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ,
        0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ,
        0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ,
        0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [49]:
a8 = a7.reshape( 4, 5 )

In [50]:
a7

array([27, 58, 48, 30, 50, 14, 42, 25, 28, 49, 55, 31, 33, 65, 13, 88, 54,
       26, 55, 86])

In [51]:
a7[3]

30

In [52]:
a7[3:8]

array([30, 50, 14, 42, 25])

In [53]:
a7[:4]

array([27, 58, 48, 30])

In [54]:
a7[18:]

array([55, 86])

In [55]:
a7[-1]

86

In [56]:
a7[0]

27

In [57]:
a7[0:1]

array([27])

In [58]:
a8

array([[27, 58, 48, 30, 50],
       [14, 42, 25, 28, 49],
       [55, 31, 33, 65, 13],
       [88, 54, 26, 55, 86]])

In [59]:
a8[2,2]

33

In [60]:
a8[2:3,2]

array([33])

In [61]:
a8[2, 2:3]

array([33])

In [62]:
a8[2:3, 2:3]

array([[33]])

In [63]:
a8[1:3, 2:4]

array([[25, 28],
       [33, 65]])

In [64]:
a8[1:, 2:]

array([[25, 28, 49],
       [33, 65, 13],
       [26, 55, 86]])

In [65]:
a8[:, 2:4]

array([[48, 30],
       [25, 28],
       [33, 65],
       [26, 55]])

In [66]:
a8[ ::, 0:2]

array([[27, 58],
       [14, 42],
       [55, 31],
       [88, 54]])

In [67]:
a8[1:]

array([[14, 42, 25, 28, 49],
       [55, 31, 33, 65, 13],
       [88, 54, 26, 55, 86]])

In [68]:
a8[ 0 ]

array([27, 58, 48, 30, 50])

In [69]:
a8[-1]

array([88, 54, 26, 55, 86])

In [70]:
a8[:2]

array([[27, 58, 48, 30, 50],
       [14, 42, 25, 28, 49]])

In [71]:
a7

array([27, 58, 48, 30, 50, 14, 42, 25, 28, 49, 55, 31, 33, 65, 13, 88, 54,
       26, 55, 86])

In [72]:
a7[4] = -1

In [73]:
a7

array([27, 58, 48, 30, -1, 14, 42, 25, 28, 49, 55, 31, 33, 65, 13, 88, 54,
       26, 55, 86])

In [74]:
# broadcasting
a7[1:3] = 100

In [75]:
a7

array([ 27, 100, 100,  30,  -1,  14,  42,  25,  28,  49,  55,  31,  33,
        65,  13,  88,  54,  26,  55,  86])

In [76]:
a8

array([[ 27, 100, 100,  30,  -1],
       [ 14,  42,  25,  28,  49],
       [ 55,  31,  33,  65,  13],
       [ 88,  54,  26,  55,  86]])

In [77]:
# broadcasting
a8[1:3, 2:4] = -1

In [78]:
a8

array([[ 27, 100, 100,  30,  -1],
       [ 14,  42,  -1,  -1,  49],
       [ 55,  31,  -1,  -1,  13],
       [ 88,  54,  26,  55,  86]])

In [79]:
# vectorization
a8[1:3, 2:4] = np.array([[1, 2], [3, 4]])

In [80]:
a8

array([[ 27, 100, 100,  30,  -1],
       [ 14,  42,   1,   2,  49],
       [ 55,  31,   3,   4,  13],
       [ 88,  54,  26,  55,  86]])

In [81]:
a7

array([ 27, 100, 100,  30,  -1,  14,  42,   1,   2,  49,  55,  31,   3,
         4,  13,  88,  54,  26,  55,  86])

In [82]:
# vectorization
a7[18:] = [-2, -3]

In [83]:
a7

array([ 27, 100, 100,  30,  -1,  14,  42,   1,   2,  49,  55,  31,   3,
         4,  13,  88,  54,  26,  -2,  -3])

In [84]:
a8

array([[ 27, 100, 100,  30,  -1],
       [ 14,  42,   1,   2,  49],
       [ 55,  31,   3,   4,  13],
       [ 88,  54,  26,  -2,  -3]])

In [85]:
# divide all the values by 100
a8 / 100

array([[ 0.27,  1.  ,  1.  ,  0.3 , -0.01],
       [ 0.14,  0.42,  0.01,  0.02,  0.49],
       [ 0.55,  0.31,  0.03,  0.04,  0.13],
       [ 0.88,  0.54,  0.26, -0.02, -0.03]])

In [86]:
# add no 1000 to all the elements
a8 + 1000

array([[1027, 1100, 1100, 1030,  999],
       [1014, 1042, 1001, 1002, 1049],
       [1055, 1031, 1003, 1004, 1013],
       [1088, 1054, 1026,  998,  997]])

In [87]:
a9 = np.random.randint(10, 100, 12).reshape(4, 3)
a9

array([[22, 23, 80],
       [65, 24, 55],
       [14, 58, 83],
       [73, 80, 54]])

In [88]:
# get all the numbers greater than 50
a9[a9 > 50]

array([80, 65, 55, 58, 83, 73, 80, 54])

In [89]:
# get all the numbers LT than 80
a9[a9 < 80]

array([22, 23, 65, 24, 55, 14, 58, 73, 54])

In [90]:
# get all the numbers between 50 and 80
a9[ (a9 >= 50) & (a9 <= 80) ]

array([80, 65, 55, 58, 73, 80, 54])

In [91]:
a9

array([[22, 23, 80],
       [65, 24, 55],
       [14, 58, 83],
       [73, 80, 54]])

In [92]:
a9 >= 50

array([[False, False,  True],
       [ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [93]:
a9 <= 80

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [94]:
(a9 >= 50) & (a9 <= 80) 

array([[False, False,  True],
       [ True, False,  True],
       [False,  True, False],
       [ True,  True,  True]])

In [95]:
# get all the numbers which are lE 20 or GE 60
a9[ (a9 <= 20) | (a9 >= 60) ]

array([80, 65, 14, 83, 73, 80])