# Python Foundation: Class 3 topics
><h3>
1. Lamda Function <br/><br/>
2. OOP concepts <br/><br/>
3. Numpy
</h3>

## Lamda - Anonymous function
> - Usually short functions, useful for simple calc and we don't have to create UDF
> - Disadvantage - Unlike UDF, can not be used multiple time

In [1]:
# Write a UDF to get the square of the number
def fn_sq(x):
    return(x ** 2)

In [ ]:
# lamda equivalant for above UDF
lambda x: x ** 2

In [ ]:
# lamda function to get sum of two numbers
lambda x, y: x + y

#### map function applies a lamda function to all the items in an iterable.

In [3]:
list(map(fn_sq, (3, 4)))

In [ ]:
# get the square of all items in the list
l1 = [1, 2, 3, 4, 5]
l1_square = []

for i in l1:
    l1_square.append(i ** 2)
l1_square

In [9]:
t1 = (1, 2, 3, 4, 5)

In [8]:
list(map(lambda x: x ** 2, t1))

[1, 4, 9, 16, 25]

In [10]:
list(map(lambda x: x ** 2, l1))

(1, 4, 9, 16, 25)

In [ ]:
# Map allows to implement this in a much simpler and nicer way.
# map(func, iterables)

l1 = [1, 2, 3, 4, 5]     ## list iterable
l1_square = list(map(lambda x: x ** 2, l1))
l1_square

In [ ]:
# Filters creates a list of elements for which a function returns true

n_list = range(-5, 5)
less_than_zero = list(filter(lambda x: x < 0, n_list))
print(less_than_zero)

In [12]:
n_list = range(-5, 5)
list(map(lambda x: x >= 0, n_list))

[False, False, False, False, False, True, True, True, True, True]

In [13]:
n_list = range(-5, 5)
list(filter(lambda x: x >= 0, n_list))

[0, 1, 2, 3, 4]

### OOP - Object oriented Programming
Encapculation
Inheritance
Polymorphism
Abstraction

## Numpy Overview

**This tutorial gives a quick overview of the numpy arrays and its features**<br>
> - **Importing numpy library**<br>
> - **Creating arrays and initializing**<br>
> - **Special initializing functions**<br>
> - **Slicing and indexing**<br>
> - **reshaping arrays**<br>
> - **Numpy Maths**<br>
> - **Combining arrays**<br>
> - **Basic algebraic operations using numpy arrays**<br>

In [14]:
# Compare the memory consumption of list and numpy array
import sys
import numpy as np

l1 = [1, 2, 3, 4, 5]
a1 = np.array(l1)

print('Size for list in bytes: ' + str(sys.getsizeof(l1)), '\nSize of numpy array in bytes: ' + str(a1.nbytes))

Size for list in bytes: 104 
Size of numpy array in bytes: 20


### Importing numpy library

In [ ]:
import numpy as np

In [27]:
l1 = [1, 2.3, 3, 4, 'a']
l1

[1, 2.3, 3, 4, 'a']

In [24]:
a = np.array([1, 2.3, 3, 4, 'a'])

In [25]:
type(a)

numpy.ndarray

In [26]:
a

array(['1', '2.3', '3', '4', 'a'], dtype='<U32')

- All numerical and mathematical functions
    - logs, arithematic calc
    - matrix operations
    - Stats functions
    - trignometric
- Pandas makes use of numpy stats functions (stats measurements, stats tests) through inheritance(internally)
- To genearte some prob distributions, we use numpy (numpy.random.xxxxx())

### Creating numpy arrays and initializing
#### 1. From python default data structures
> list, tuple

In [ ]:
# Create one dimensional array
# array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
a1 = np.array([23, 44, 33, 66, 77, 88, 99, 12])

In [ ]:
type(a1)

In [ ]:
# Create a two dimensional array
a2 = np.array([[23, 44, 33, 66], [77, 88, 99, 12]])

In [30]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### 2. From random data, or all zeros or all ones etc
>zeros, ones, eye, full, random, diag

In [ ]:
a1 = np.zeros((4,3))  # Create an array of all zeros

In [34]:
np.zeros((5, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.empty((3, 3), dtype = str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a2 = np.ones((4, 2)) # Create an array of all ones

In [44]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [52]:
np.full((3, 4), 34, dtype = float)

array([[34., 34., 34., 34.],
       [34., 34., 34., 34.],
       [34., 34., 34., 34.]])

In [47]:
np.random.random((3, 4))

array([[0.69694392, 0.04068192, 0.74835001, 0.06731385],
       [0.76805466, 0.24283163, 0.87598337, 0.46772577],
       [0.94488051, 0.39446422, 0.01390141, 0.06247785]])

In [51]:
np.random.randint(50, 100, size = (2, 3))

array([[76, 82, 74],
       [73, 99, 66]])

In [ ]:
a3  = np.arange(10) # Create an array with regularly incrementing values from start to end - 1

In [ ]:
a4 = np.empty((3, 5)) # Create an empty array, with uninitialized values

In [ ]:
a5 = np.eye(3) # Create identity matrix
a5 = np.identity(4)

In [ ]:
a6 = np.full((2,2), 7)

In [ ]:
a7 = np.random.random((2,2))

In [ ]:
a8 = np.random.randint(100, size = (4,4))

In [53]:
a9 = np.diag?

In [55]:
a = np.arange(10)
a9 = np.diag(a)
a9

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

### Reshape the arrays
>reshape, transpose

In [74]:
a1 = np.array([1,5,4,3,5,4,3,2,7,6,5,4])
a1

array([1, 5, 4, 3, 5, 4, 3, 2, 7, 6, 5, 4])

In [57]:
a1.reshape(2, 6)

array([[1, 5, 4, 3, 5, 4],
       [3, 2, 7, 6, 5, 4]])

In [81]:
a2 = a1.reshape(2, 6)

In [82]:
a2.reshape(6, 2)

array([[1, 5],
       [4, 3],
       [5, 4],
       [3, 2],
       [7, 6],
       [5, 4]])

In [87]:
a2.transpose()

array([[1, 3],
       [5, 2],
       [4, 7],
       [3, 6],
       [5, 5],
       [4, 4]])

In [89]:
a2.resize((4, 5))

ValueError: cannot resize this array: it does not own its data

### Inspection of numpy arrays
>- Get the size of the array
>- Get the shape of array
>- No of dimensions
>- etc...


In [91]:
# Create a numpy array
a = np.arange(1, 21).reshape(5, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [92]:
# Get the size of the array
a.size

20

In [93]:
# Get the shape of the array
a.shape

(5, 4)

In [94]:
# No of dimensions of the array
a.ndim

2

In [95]:
# Get the data type of the elements in the array
a.dtype

dtype('int32')

In [96]:
# Bytes consumed by array elements
a.nbytes

80

### Slicing & Indexing an array 

In [123]:
a1 = np.arange(21)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [109]:
a1[low, high - 1]

7

In [124]:
a1[6]

6

In [125]:
a1[6:13]

array([ 6,  7,  8,  9, 10, 11, 12])

In [126]:
a1[13: 6]

array([], dtype=int32)

In [127]:
a1[13: 6:-1]

array([13, 12, 11, 10,  9,  8,  7])

In [128]:
# Create a numpy array
a1 = np.arange(1, 21).reshape(5, 4)

In [129]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [133]:
a1[2,2]

11

In [137]:
a1[2:4, 1:3]

array([[10, 11],
       [14, 15]])

In [ ]:
a1[

In [107]:
a1[0:1,:]

array([[1, 2, 3, 4]])

In [113]:
# get the third row
a1[2]

array([17, 18, 19, 20])

In [114]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [119]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
np.array(range(1, 10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
np.array(range(10, 1))

array([], dtype=float64)

In [122]:
np.array(range(10, 1, -1))

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
np.array(range(2,1, -1))

In [118]:
a1[2:1:-1]

array([[ 9, 10, 11, 12]])

In [ ]:
# Get first row
a1[0]

In [ ]:
# Get 1 and 2 row
a1[0:2]

In [ ]:
# Get 1 and 2 row and second column
a1[0:2, 1]

In [ ]:
# Get data from first column
a1[:, 0]

In [ ]:
# Get specific elements
np.array([a1[0,1], a1[2,2]])

In [140]:
l1 = [1, 2, 3, 4, 5]

In [141]:
l1

[1, 2, 3, 4, 5]

In [142]:
l1 + 5

TypeError: can only concatenate list (not "int") to list

In [143]:
a1 = np.array(l1)

In [144]:
a1 + 5

array([ 6,  7,  8,  9, 10])

In [145]:
a1 = np.arange(1, 21).reshape(5, 4)
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [149]:
# Boolean indexing: Check which items in array meet following condition
a1 >= 9

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [150]:
# Index the data in array basis conditions
a1[a1 >= 9]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### Updating an array

In [2]:
import numpy as np

In [20]:
a1 = np.random.randint(50, 100, size = (4, 6))

In [6]:
a1

array([[61, 67, 86, 73, 75, 66],
       [60, 79, 81, 93, 62, 57],
       [77, 64, 73, 50, 82, 86],
       [55, 53, 50, 51, 71, 52]])

In [7]:
a1[1,1] = 0

In [8]:
a1

array([[61, 67, 86, 73, 75, 66],
       [60,  0, 81, 93, 62, 57],
       [77, 64, 73, 50, 82, 86],
       [55, 53, 50, 51, 71, 52]])

In [10]:
a1 > 85

array([[False, False,  True, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False,  True],
       [False, False, False, False, False, False]])

In [11]:
a1[a1 > 85] = 85

In [12]:
a1

array([[61, 67, 85, 73, 75, 66],
       [60,  0, 81, 85, 62, 57],
       [77, 64, 73, 50, 82, 85],
       [55, 53, 50, 51, 71, 52]])

In [13]:
a1.mean()

63.958333333333336

In [14]:
a1.sum()

1535

In [16]:
a1.min()

0

In [17]:
a1.max()

85

In [ ]:
# update the values in the array by the mean where the values are <= 60

In [18]:
a1 [a1 <= 60] = a1.mean()

In [19]:
a1

array([[61, 67, 85, 73, 75, 66],
       [63, 63, 81, 85, 62, 63],
       [77, 64, 73, 63, 82, 85],
       [63, 63, 63, 63, 71, 63]])

In [21]:
a1 <= 60

array([[False, False,  True, False,  True, False],
       [False, False, False, False, False,  True],
       [False, False, False,  True,  True, False],
       [False, False, False,  True,  True, False]])

In [22]:
a1 >= 90

array([[False, False, False,  True, False, False],
       [False, False, False, False,  True, False],
       [False,  True,  True, False, False, False],
       [False, False, False, False, False, False]])

In [25]:
'''and: &
or |
not -
'''

a1[(a1 <= 60) | (a1 >= 90)] = a1.mean()

In [26]:
a1

array([[89, 65, 74, 74, 74, 68],
       [82, 88, 78, 70, 74, 74],
       [81, 74, 74, 74, 74, 82],
       [80, 63, 89, 74, 74, 80]])

In [ ]:
# Data imputation in numpy basis slicing
arr_1[2, 1] = 0

In [ ]:
# Data imputation in numpy basis indexing
arr_1[arr_1 >= 95] = 10

In [ ]:
# Data imputaion with mean of original data
arr_1[arr_1 >= 90] = a1.mean()

In [27]:
a1

array([[89, 65, 74, 74, 74, 68],
       [82, 88, 78, 70, 74, 74],
       [81, 74, 74, 74, 74, 82],
       [80, 63, 89, 74, 74, 80]])

In [30]:
a1 [2:, 3:] = 'a'

ValueError: invalid literal for int() with base 10: 'a'

In [29]:
a1

array([[89, 65, 74, 74, 74, 68],
       [82, 88, 78, 70, 74, 74],
       [81, 74, 74,  0,  0,  0],
       [80, 63, 89,  0,  0,  0]])

In [ ]:
# Data imputaion with multiple conditions
arr_1[(arr_1 >= 90) | (arr_1 <= 60)] = 10

### Combine data from arrays 

In [45]:
x = np.random.randint( 10, size = (6,9))
y = np.random.randint( 100, size = (6,2))

In [46]:
x

array([[2, 7, 7, 3, 5, 0, 9, 0, 5],
       [3, 6, 9, 4, 4, 0, 7, 0, 3],
       [4, 9, 1, 9, 1, 0, 3, 1, 6],
       [3, 4, 5, 1, 8, 6, 8, 6, 8],
       [6, 3, 3, 1, 3, 3, 8, 1, 7],
       [4, 6, 1, 9, 8, 9, 2, 9, 5]])

In [47]:
y

array([[ 1,  2],
       [45, 16],
       [63, 56],
       [32, 56],
       [40, 17],
       [85, 31]])

In [43]:
# combine the data vertically
np.vstack([x, y])

array([[ 8,  1],
       [ 4,  2],
       [70,  8],
       [ 5, 41],
       [63, 80],
       [89, 11],
       [85, 66],
       [85, 26]])

In [48]:
np.hstack([x, y])

array([[ 2,  7,  7,  3,  5,  0,  9,  0,  5,  1,  2],
       [ 3,  6,  9,  4,  4,  0,  7,  0,  3, 45, 16],
       [ 4,  9,  1,  9,  1,  0,  3,  1,  6, 63, 56],
       [ 3,  4,  5,  1,  8,  6,  8,  6,  8, 32, 56],
       [ 6,  3,  3,  1,  3,  3,  8,  1,  7, 40, 17],
       [ 4,  6,  1,  9,  8,  9,  2,  9,  5, 85, 31]])

In [ ]:
# combine the data horizontally
np.hstack([x, y])

### Mathematical calculations on numpy arrays
> Addition, Substraction, Multiplication and other matrix operations

In [58]:
x = np.random.randint( 100, size = (3,3) )
y = np.random.randint( 100, size = (3,1) )

In [59]:
x

array([[98, 87, 45],
       [95, 75, 85],
       [ 6, 77, 44]])

In [60]:
y

array([[16],
       [47],
       [10]])

In [61]:
# Add two matrices x + y or np.add( x, y )
x + y

array([[114, 103,  61],
       [142, 122, 132],
       [ 16,  87,  54]])

In [53]:
# np.substract( x, y )
x - y

array([[-28,   9, -13],
       [ -6, -13, -78],
       [-35,  17,  81]])

In [ ]:
# np.multiply( x, y )
x * y

### Calculating column sums and row sums (axis option)

In [2]:
x = np.random.randint( 10, size = (4,4) )
x

array([[9, 9, 0, 5],
       [9, 7, 4, 8],
       [9, 1, 7, 8],
       [4, 7, 0, 5]])

In [65]:
# Get the sum mean and median
print(x.sum(), x.mean(), x.std())

59 3.6875 2.39057393736316


In [4]:
np.sum?

In [3]:
# To get summary row wise, use axis = 1
np.sum(x, axis = 1)

array([23, 28, 25, 16])

In [70]:
x.sum(axis = 1)

array([20,  6, 11, 22])

In [71]:
np.sum(x, axis = )